### ISSUE TITLE
build issue: python 2 missing ?

### ISSUE THREAD

**Issue by SkybuckFlying** [vitelabs/vite-wallet#66]
I ran into two build issues.

I followed tutorial to try and build desktop wallet here:

https://github.com/vitelabs/vite-wallet

1. First issue is minor:

cd ../vite-web-wallet is wrong, should be:
cd vite-web-wallet

2. Second issue: python 2 missing ?

```
[4/4] Building fresh packages...
[14/24] ⠈ scrypt
[-/24] ⠈ waiting...
[13/24] ⠈ websocket
[23/24] ⠈ node-sass
error V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\node-sass
Output:
Building: G:\Tools\NodeJS\node.exe V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsas
s_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'G:\\Tools\\NodeJS\\node.exe',
gyp verb cli   'V:\\ViteDesktopWallet\\vite-wallet\\vite-web-wallet\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@21.6.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:80:29)
gyp verb `which` failed     at V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:89:16
gyp verb `which` failed     at V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:80:29)
gyp verb `which` failed     at V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\which\which.js:89:16
gyp verb `which` failed     at V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python312\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python312\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at genericNodeError (node:internal/errors:984:15)
gyp ERR! stack     at wrappedFn (node:internal/errors:538:14)
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "G:\\Tools\\NodeJS\\node.exe" "V:\\ViteDesktopWallet\\vite-wallet\\vite-web-wallet\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=
" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\node-sass
gyp ERR! node -v v21.6.2

```

There may have also be some install issues, repeating it gives this log, not sure if this is problem as well, maybe not:

```
$ npm install node-sass
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-transform-arrow-functions@7.0.0-beta.53
npm WARN Found: @babel/core@7.13.8
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.0.0" from babel-loader@8.2.2
npm WARN   node_modules/babel-loader
npm WARN     dev babel-loader@"^8.0.2" from the root project
npm WARN     1 more (testwebworker)
npm WARN   76 more (babel-plugin-polyfill-corejs2, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/plugin-transform-arrow-functions@7.0.0-beta.53
npm WARN node_modules/@babel/plugin-transform-arrow-functions
npm WARN   @babel/plugin-transform-arrow-functions@"7.0.0-beta.53" from @babel/preset-es2015@7.0.0-beta.53
npm WARN   node_modules/@babel/preset-es2015
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.0.0-beta.56
skybu@SuperPC2023 MINGW64 /v/ViteDesktopWallet/vite-wallet/vite-web-wallet ((5f0d7ca3...))
$ npm install node-sass
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-transform-arrow-functions@7.0.0-beta.53
npm WARN Found: @babel/core@7.13.8
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.0.0" from babel-loader@8.2.2
npm WARN   node_modules/babel-loader
npm WARN     dev babel-loader@"^8.0.2" from the root project
npm WARN     1 more (testwebworker)
npm WARN   76 more (babel-plugin-polyfill-corejs2, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/plugin-transform-arrow-functions@7.0.0-beta.53
npm WARN node_modules/@babel/plugin-transform-arrow-functions
npm WARN   @babel/plugin-transform-arrow-functions@"7.0.0-beta.53" from @babel/preset-es2015@7.0.0-beta.53
npm WARN   node_modules/@babel/preset-es2015
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.0.0-beta.56
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/plugin-transform-arrow-functions@7.0.0-beta.53
npm WARN   node_modules/@babel/plugin-transform-arrow-functions
npm WARN     @babel/plugin-transform-arrow-functions@"7.0.0-beta.53" from @babel/preset-es2015@7.0.0-beta.53
npm WARN     node_modules/@babel/preset-es2015
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-transform-block-scoped-functions@7.0.0-beta.53
npm WARN Found: @babel/core@7.13.8
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.0.0" from babel-loader@8.2.2
npm WARN   node_modules/babel-loader
npm WARN     dev babel-loader@"^8.0.2" from the root project
npm WARN     1 more (testwebworker)
npm WARN   76 more (babel-plugin-polyfill-corejs2, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/plugin-transform-block-scoped-functions@7.0.0-beta.53
npm WARN node_modules/@babel/plugin-transform-block-scoped-functions
npm WARN   @babel/plugin-transform-block-scoped-functions@"7.0.0-beta.53" from @babel/preset-es2015@7.0.0-beta.53
npm WARN   node_modules/@babel/preset-es2015
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.0.0-beta.56
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/plugin-transform-block-scoped-functions@7.0.0-beta.53
npm WARN   node_modules/@babel/plugin-transform-block-scoped-functions
npm WARN     @babel/plugin-transform-block-scoped-functions@"7.0.0-beta.53" from @babel/preset-es2015@7.0.0-beta.53
npm WARN     node_modules/@babel/preset-es2015
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-transform-block-scoping@7.0.0-beta.53
npm WARN Found: @babel/core@7.13.8
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.0.0" from babel-loader@8.2.2
npm WARN   node_modules/babel-loader
npm WARN     dev babel-loader@"^8.0.2" from the root project
npm WARN     1 more (testwebworker)
npm WARN   76 more (babel-plugin-polyfill-corejs2, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/plugin-transform-block-scoping@7.0.0-beta.53
npm WARN node_modules/@babel/plugin-transform-block-scoping
npm WARN   @babel/plugin-transform-block-scoping@"7.0.0-beta.53" from @babel/preset-es2015@7.0.0-beta.53
npm WARN   node_modules/@babel/preset-es2015



```
I will try and install python 2 and then re-try build to see if that helps.

**Comment by SkybuckFlying** [comment]
After installing python2 and trying to rebuild both this is the new error output:

```
skybu@SuperPC2023 MINGW64 /v/ViteDesktopWallet/vite-wallet (master)
$ yarn build:win
yarn run v1.22.19
warning package.json: No license field
$ FORCE_COLOR=1 p=WIN npm run build
'FORCE_COLOR' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

skybu@SuperPC2023 MINGW64 /v/ViteDesktopWallet/vite-wallet (master)
$ yarn
yarn install v1.22.19
warning package.json: No license field
(node:24696) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning vite-wallet@1.7.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.22s.

skybu@SuperPC2023 MINGW64 /v/ViteDesktopWallet/vite-wallet (master)
$ cd vite-web-wallet

skybu@SuperPC2023 MINGW64 /v/ViteDesktopWallet/vite-wallet/vite-web-wallet ((5f0d7ca3...))
$ yarn
yarn install v1.22.19
warning package.json: "dependencies" has dependency "@babel/plugin-proposal-class-properties" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with version "^7
.5.0"
warning package.json: "dependencies" has dependency "@babel/plugin-proposal-object-rest-spread" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with version "
^7.5.4"
warning package.json: "dependencies" has dependency "@babel/preset-typescript" with range "~7.3.3" that collides with a dependency in "devDependencies" of the same name with version "^7.3.3"
warning ..\package.json: No license field
warning vite-wallet@4.0.0: "dependencies" has dependency "@babel/plugin-proposal-class-properties" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with versio
n "^7.5.0"
warning vite-wallet@4.0.0: "dependencies" has dependency "@babel/plugin-proposal-object-rest-spread" with range "~7.5.5" that collides with a dependency in "devDependencies" of the same name with vers
ion "^7.5.4"
warning vite-wallet@4.0.0: "dependencies" has dependency "@babel/preset-typescript" with range "~7.3.3" that collides with a dependency in "devDependencies" of the same name with version "^7.3.3"
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > @babel/preset-es2015@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-arrow-functions@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-block-scoped-functions@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-block-scoping@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-classes@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-computed-properties@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-destructuring@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-duplicate-keys@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-for-of@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-function-name@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-instanceof@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-literals@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-amd@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-commonjs@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-systemjs@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-modules-umd@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-object-super@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-parameters@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-regenerator@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-shorthand-properties@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-spread@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-sticky-regex@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-template-literals@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-typeof-symbol@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning "testwebworker > @babel/preset-es2015 > @babel/plugin-transform-unicode-regex@7.0.0-beta.53" has incorrect peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
warning " > eslint-plugin-vue@4.7.1" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
[4/4] Building fresh packages...
[18/24] ⠄ gifsicle
[13/24] ⠄ websocket
[14/24] ⠄ scrypt
[19/24] ⠄ mozjpeg
error V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3
Output:
V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3>if not defined npm_config_node_gyp (node "G:\Tools\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@21.6.2 | win32 | x64
gyp info find Python using Python version 3.12.2 found at "C:\Python312\python.exe"

gyp info find VS using VS2022 (17.8.34316.72) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python312\python.exe
gyp info spawn args [
gyp info spawn args 'G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'V:\\ViteDesktopWallet\\vite-wallet\\vite-web-wallet\\node_modules\\sha3\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\skybu\\AppData\\Local\\node-gyp\\Cache\\21.6.2\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\Users\\skybu\\AppData\\Local\\node-gyp\\Cache\\21.6.2',
gyp info spawn args '-Dnode_gyp_dir=G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\skybu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.6.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=V:\\ViteDesktopWallet\\vite-wallet\\vite-web-wallet\\node_modules\\sha3',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'V:\\ViteDesktopWallet\\vite-wallet\\vite-web-wallet\\node_modules\\sha3\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]

  addon.cpp
V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,23): error C2039: 'AccessorSignature': is not a member of 'v8' [V:\ViteDesktopWallet\vite-wallet\
vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8.h(71,11):
  see declaration of 'v8'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,23): error C2065: 'AccessorSignature': undeclared identifier [V:\ViteDesktopWallet\vite-wallet\vi
te-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,13): error C2923: 'v8::Local': 'AccessorSignature' is not a valid template type argument for para
meter 'T' [V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,23):
  see declaration of 'AccessorSignature'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan_callbacks.h(55,42): error C2955: 'v8::Local': use of class template requires template argument list [V:\ViteDesk
topWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-local-handle.h(242,13):
  see declaration of 'v8::Local'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,14): error C2955: 'v8::Local': use of class template requires template argument list [V:\ViteDesktopWalle
t\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-local-handle.h(242,13):
  see declaration of 'v8::Local'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2641: cannot deduce template arguments for 'v8::Local' [V:\ViteDesktopWallet\vite-wallet\vite
-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(const v8::LocalBase<T> &)': expects 1 arguments - 0 provided [V
:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-local-handle.h(378,3):
  see declaration of 'v8::Local'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(v8::Local<S>)': expects 1 arguments - 0 provided [V:\ViteDeskto
pWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-local-handle.h(247,3):
  see declaration of 'v8::Local'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2783: 'v8::Local<T> v8::Local(void)': could not deduce template argument for 'T' [V:\ViteDesk
topWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-local-handle.h(244,3):
  see declaration of 'v8::Local'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2444,34): error C2780: 'v8::Local<T> v8::Local(v8::Local<T>)': expects 1 arguments - 0 provided [V:\ViteDeskto
pWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-local-handle.h(242,13):
  see declaration of 'v8::Local'

V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6): error C2665: 'v8::ObjectTemplate::SetAccessor': no overloaded function could convert all the argument
 types [V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\build\sha3.vcxproj]
  (compiling source file '../src/addon.cpp')
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-template.h(816,8):
  could be 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::Side
EffectType,v8::SideEffectType)'
        V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6):
        'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEff
ectType,v8::SideEffectType)': cannot convert argument 7 from 'Nan::imp::Sig' to 'v8::SideEffectType'
                V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2477,7):
                No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  C:\Users\skybu\AppData\Local\node-gyp\Cache\21.6.2\include\node\v8-template.h(809,8):
  or       'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffect
Type,v8::SideEffectType)'
        V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6):
        'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,v8::AccessControl,v8::PropertyAttribute,v8::SideEffectTyp
e,v8::SideEffectType)': cannot convert argument 2 from 'Nan::imp::NativeGetter' to 'v8::AccessorGetterCallback'
                V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2472,7):
                This conversion requires a reinterpret_cast, a C-style cast or parenthesized function-style cast
  V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3\node_modules\nan\nan.h(2470,6):
  while trying to match the argument list '(v8::Local<v8::String>, Nan::imp::NativeGetter, Nan::imp::NativeSetter, v8::Local<v8::Object>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)'

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (G:\Tools\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "G:\\Tools\\NodeJS\\node.exe" "G:\\Tools\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd V:\ViteDesktopWallet\vite-wallet\vite-web-wallet\node_modules\sha3

```
